rbacCreate: true
serviceAccountCreate: true
podSecurityPolicyEnabled: true
networkPolicyEnabled: true

persistence:
  enabled: false
  existingClaim:
  storageClass:
  # NOTE: Google does not support ReadWriteMany
  # --> all containers will be placed on the same Kubernetes node
  accessMode: ReadWriteOnce
  size: 8Gi

ingress:
  class: ''
  tls: true
  domains:

serviceDefaults:
  # Basics
  image: # For 3rd party container image
  command:
  port: 8080
  tier:
  livenessPath: /healthz
  livenessInitialDelay: 3
  # Paths
  paths:
    # - path:
    #   basicAuthEnabled:
    #   basicAuthHtpasswdSecret:
    #   clientMaxBodySize:
    #   bufferSize:
    #   requestBuffering:
    #   connectTimeout:
    #   sendTimeout:
    #   readTimeout:
    #   nextUpstreamTimeout:
    #   limitRate:
    #   limitRateAfter:
    #   rewriteTarget:
    #   rewriteTargetDisabled:
  # Path defaults
  basicAuthEnabled: ${taito_basic_auth_enabled}
  basicAuthHtpasswdSecret: ${taito_project}-${taito_env}-basic-auth
  # clientMaxBodySize: 1m
  # bufferSize: 4k
  # requestBuffering: on
  # connectTimeout: 5
  # sendTimeout: 60
  # readTimeout: 60
  # nextUpstreamTimeout: 0
  limitRate:
  limitRateAfter:
  rewriteTarget:
  rewriteTargetDisabled:
  # Security
  runAsUser:
  runAsGroup:
  privileged: false
  allowPrivilegeEscalation: false
  capabilities:
  # - NET_ADMIN (example)
  # Resources
  cpuRequest: 2m
  cpuLimit: 100m
  memoryRequest: 50Mi
  memoryLimit: 512Mi
  # Vertical scaling
  verticalScaleUpdateMode: Off
  # Horizontal autoscaling
  replicas: 2
  autoscale: false
  autoscaleCpuPercentage: 70
  autoscaleMemoryPercentage: 70
  minReplicas: 2
  maxReplicas: 5
  # TODO metrics:
  # https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/
  # TODO vertical autoscaling:
  # https://cloud.google.com/kubernetes-engine/docs/how-to/vertical-pod-autoscaling
  # Sidecar
  sidecar:
  # Mounts
  temporaryVolumeMounts:
    # - mountPath: /mnt/data
    #   volumePath: data
    #   readOnly: false
  persistentVolumeMounts:
    # - mountPath: /mnt/data
    #   volumePath: data
    #   readOnly: false
  # Devices
  hostDevices:
    # - name: dev-tun
    #   path: /dev/net/tun
    #   type: CharDevice
    #   readOnly: false
  # Env
  secrets:
    # Secrets as mounted files
  secretEnv:
    # Secrets as environment variables (not recommended)
  env:

services:
