rbac:
  create: true
serviceAccount:
  create: true
podSecurityPolicy:
  enabled: true

persistence:
  enabled: false
  existingClaim:
  storageClass:
  # NOTE: Google does not support ReadWriteMany
  # --> all containers will be placed on the same Kubernetes node
  accessMode: ReadWriteOnce
  size: 8Gi

ingress:
  class: nginx
  tls: true
  maxBodySize: 1m
  basicAuth:
    enabled: true
    htpasswdSecret:
  domains:

serviceDefaults:
  # Basics
  image: # For 3rd party container image
  command:
  path:
  port: 8080
  tier:
  livenessPath: /healthz
  livenessInitialDelay: 30
  # Security
  runAsUser:
  fsGroup:
  # Resources
  cpuRequest: 2m
  cpuLimit: 100m
  memoryRequest: 50Mi
  memoryLimit: 256Mi
  # Scaling
  replicas: 1
  autoscale: false
  minReplicas: 2
  maxReplicas: 5
  # TODO metrics:
  # https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/
  # TODO vertical autoscaling:
  # https://cloud.google.com/kubernetes-engine/docs/how-to/vertical-pod-autoscaling
  # Sidecar
  sidecar:
  # Mounts
  temporaryVolumeMounts:
    # - mountPath: /mnt/data
    #   volumePath: data
    #   readOnly: false
  persistentVolumeMounts:
    # - mountPath: /mnt/data
    #   volumePath: data
    #   readOnly: false
  # Env
  env:
    # Environment variables
  secrets:
    # Secrets

services:
