# Global settings for all charts
global:
  # These are given as command line parameters during build
  zone:
    name: asdf
    provider: adsf
    providerRegion: asdf
    providerZone: asdf
    namespace: asdf
    resourceNamespace: adsf
  project:
    name: asdf
    company: asdf
    family: asdf
    application: asdf
    suffix: asdf
  build:
    version: asdf
    commit: asdf
    imageTag: adsf
  # Common settings
  logFormat: stackdriver
  logLevel: info # trace, debug, info, warn, error, fatal
  registry:
  imagePullPolicy: ''
  debug: false

serviceAccountCreate: true
networkPolicyEnabled: true
networkPolicyProvider: CALICO
podSecurityPolicyCreate: false

persistence:
  enabled: false
  existingClaim:
  storageClass:
  # NOTE: Google does not support ReadWriteMany
  # --> all containers will be placed on the same Kubernetes node
  accessMode: ReadWriteOnce
  size: 8Gi

ingress:
  class: ''
  oldRewritePolicy: false
  oldAcmeCertificate: false
  tls: true
  certManagerEnabled: true
  domains:

serviceDefaults:
  # Basics
  image: # For 3rd party container image
  command:
  initCommand:
  port: 8080
  tier:
  livenessPath: /healthz
  # livenessCommand:
  livenessInitialDelay: 3
  # Paths
  paths:
    # - path:
    #   basicAuthEnabled:
    #   basicAuthHtpasswdSecret:
    #   clientMaxBodySize:
    #   bufferSize:
    #   requestBuffering:
    #   connectTimeout:
    #   sendTimeout:
    #   readTimeout:
    #   nextUpstreamTimeout:
    #   limitRate:
    #   limitRateAfter:
    #   rewriteTarget:
    #   rewriteTargetDisabled:
  # Security
  modsecurityEnabled: true
  serviceAccountRoles: []
  basicAuthEnabled: ${taito_basic_auth_enabled}
  basicAuthHtpasswdSecret: ${taito_project}-${taito_env}-basic-auth
  # Path defaults
  # clientMaxBodySize: 1k
  # bufferSize: 4k
  # requestBuffering: on
  # connectTimeout: 5
  # sendTimeout: 60
  # readTimeout: 60
  # nextUpstreamTimeout: 0
  limitRate:
  limitRateAfter:
  rewriteTarget:
  rewriteTargetDisabled:
  # Security
  serviceAccountName:
  runAsUser:
  runAsGroup:
  fsGroup:
  privileged: false
  allowPrivilegeEscalation: false
  capabilities:
  # Network
  httpProxyImage: taitounited/squid:4.12
  # - NET_ADMIN (example)
  # Resources
  cpuRequest: 20m
  cpuLimit: 100m
  memoryRequest: 70Mi
  memoryLimit: 256Mi
  gpuLimit:
  # Strategy
  strategyType: RollingUpdate
  # Vertical scaling
  verticalScaleUpdateMode: Off
  # Horizontal autoscaling
  replicas: 2
  autoscale: false
  autoscaleCpuPercentage: 70
  autoscaleMemoryPercentage: 70
  minReplicas: 2
  maxReplicas: 5
  # Placement
  placementSameAs:
  # TODO metrics:
  # https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/
  # TODO vertical autoscaling:
  # https://cloud.google.com/kubernetes-engine/docs/how-to/vertical-pod-autoscaling
  # Sidecar
  sidecar:
  # Mounts
  temporaryVolumeMounts:
    # - mountPath: /mnt/data
    #   volumePath: data
    #   readOnly: false
  persistentVolumeMounts:
    # - mountPath: /mnt/data
    #   volumePath: data
    #   readOnly: false
  # Devices
  hostDevices:
    # - name: dev-tun
    #   path: /dev/net/tun
    #   type: CharDevice
    #   readOnly: false
  # Env
  secrets:
    # Secrets as mounted files
  secretEnv:
    # Secrets as environment variables (not recommended)
  env:

services:
