{{- range $sa := .Values.serviceAccounts }}
apiVersion: v1
kind: ServiceAccount
metadata:
  {{- if $sa.id }}
  name: {{ $sa.id }}
  {{- else }}
  name: {{ $sa.name }}
  {{- end }}
  {{- if $sa.namespace }}
  namespace: {{ $sa.namespace }}
  {{- end }}
---
{{- end }}
