{{- if .Values.permissions.clusterRoles }}
{{- range $role := .Values.permissions.clusterRoles }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ $role.name }}
subjects:
{{- range $name := $role.subjects }}
{{- if eq (split ":" $name)._0 "domain" }}
- kind: Group
  name: allusers@split(",", $name)[1]
{{- else if eq (split ":" $name)._0 "group" }}
- kind: Group
  name: (split ":" $name)._1
{{- else }}
- kind: User
  name: (split ":" $name)._1
{{- end }}
{{- end }}
roleRef:
  kind: ClusterRole
  name: {{ $role.name }}
  apiGroup: rbac.authorization.k8s.io
---
{{- end }}
{{- end }}
