{{- if .Values.provider }}
{{- if eq .Values.provider "gcp" }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: fast
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd
{{- end }}
{{- end }}
