{{- if .Values.ingress.tls }}
{{- if .Values.ingress.certManagerEnabled }}

{{- $cert := dict "required" false -}}
{{- range $domain := .Values.ingress.domains }}
{{- if not $domain.certSecret }}
{{- $dummy := set $cert "required" true -}}
{{- end }}
{{- end }}
{{- if $cert.required }}

{{- if .Values.ingress.oldRewritePolicy }}
apiVersion: certmanager.k8s.io/v1alpha1
{{- else }}
apiVersion: cert-manager.io/v1
{{- end }}
kind: Certificate
metadata:
  name: {{ template "fullname" . }}-certificate
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  secretName: {{ template "fullname" . }}-ssl
  issuerRef:
    name: letsencrypt-issuer
    kind: ClusterIssuer
  dnsNames:
    {{- range $domain := .Values.ingress.domains }}
    {{- if not $domain.certSecret }}
    - {{ $domain.name }}
    {{- range $altDomain := $domain.altDomains }}
    {{- if $altDomain.name }}
    - {{ $altDomain.name }}
    {{- end }}
    {{- end }}
    {{- end }}
    {{- end }}
  {{- if .Values.ingress.oldRewritePolicy }}
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
        {{- range $domain := .Values.ingress.domains }}
        {{- if not $domain.certSecret }}
        - {{ $domain.name }}
        {{- range $altDomain := $domain.altDomains }}
        {{- if $altDomain.name }}
        - {{ $altDomain.name }}
        {{- end }}
        {{- end }}
        {{- end }}
        {{- end }}
  {{- end }}

{{- end }}

{{- end }}
{{- end }}
