{{- if .Values.ingress.tls }}
{{- if .Values.ingress.certManagerEnabled }}

{{- $cert := dict "required" false -}}
{{- range $domain := .Values.ingress.domains }}
{{- if not $domain.certSecret }}
{{- $dummy := set $cert "required" true -}}
{{- end }}
{{- end }}
{{- if $cert.required }}

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ template "myfullname" . }}-certificate
spec:
  secretName: {{ template "myfullname" . }}-ssl
  issuerRef:
    name: {{ .Values.ingress.issuer | default "letsencrypt-issuer" }} 
    kind: ClusterIssuer
  dnsNames:
    {{- range $domain := .Values.ingress.domains }}
    {{- if not $domain.certSecret }}
    - {{ $domain.name }}
    {{- range $altDomain := $domain.altDomains }}
    {{- if $altDomain.name }}
    - {{ $altDomain.name }}
    {{- end }}
    {{- end }}
    {{- end }}
    {{- end }}

{{- end }}

{{- end }}
{{- end }}
