# TODO: If configmap is changed, the pods are not restarted if image tag
# does not change --> they keep using the old values
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "myfullname" . }}-common
data:
  ENV: {{ .Values.global.env | default "" | quote }}
  DEBUG: {{ .Values.global.debug | default "false" | quote }}
  LOG_PROVIDER: {{ .Values.global.logProvider | default "" | quote }}
  LOG_FORMAT: {{ .Values.global.logFormat | default "" | quote }}
  LOG_LEVEL: {{ .Values.global.logLevel | default "" | quote }}
  PROJECT: {{ .Values.global.project.name | default "" | quote }}
  COMPANY: {{ .Values.global.project.company | default "" | quote }}
  FAMILY: {{ .Values.global.project.family | default "" | quote }}
  APPLICATION: {{ .Values.global.project.application | default "" | quote }}
  SUFFIX: {{ .Values.global.project.suffix | default "" | quote }}
  DOMAIN: {{ .Values.global.domain | quote }}
  PUBLIC_PORT: {{ .Values.global.publicPort | default "" | quote }}
  URL: {{ .Values.global.url | default "" | quote }}
  VERSION: {{ .Values.global.build.version | default "" | quote }}
  COMMIT: {{ .Values.global.build.commit | default "" | quote }}
  IMAGE_TAG: {{ .Values.global.build.imageTag | default "" | quote }}
  DEPLOY_TIME: {{ now | htmlDate }}
