{{- $root := . -}}
{{- $env := .Values.global.env -}}
{{- $global := .Values.global -}}
{{- $provider := .Values.global.zone.provider -}}
{{- $defaults := .Values.serviceDefaults -}}

{{- range $serviceName, $service := .Values.services }}
{{- with $service }}
{{- if or (not (hasKey . "enabled")) (.enabled) }}
{{- range $job := .cronJobs }}
{{- with (index $root.Values.services $serviceName) }}
{{- if .verticalScaleUpdateMode }}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ template "fullname" $root }}-{{ $serviceName }}-{{ $job.name }}
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: CronJob
    name: {{ template "fullname" $root }}-{{ $serviceName }}-{{ $job.name }}
  updatePolicy:
    updateMode: {{ .verticalScaleUpdateMode }}
---
{{- end }}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ template "fullname" $root }}-{{ $serviceName }}-{{ $job.name }}
  # TODO: access labels for cronjobs also
spec:
  schedule: {{ $job.schedule | quote }}
  concurrencyPolicy: {{ $job.concurrencyPolicy | default "Forbid" }}
  failedJobsHistoryLimit: {{ $job.failedJobsHistoryLimit | default 1 }}
  startingDeadlineSeconds: {{ $job.startingDeadlineSeconds | default nil }}
  successfulJobsHistoryLimit: {{ $job.successfulJobsHistoryLimit | default 3 }}
  suspend: {{ $job.suspend | default false }}
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: {{ $job.restartPolicy | default "OnFailure" }}
          securityContext:
            {{- if quote $job.fsGroup }}
            fsGroup: {{ $job.fsGroup }}
            {{- end }}
          {{- if default $defaults.serviceAccountName $job.serviceAccountName }}
          serviceAccountName: {{ default $defaults.serviceAccountName $job.serviceAccountName }}
          {{- else }}
          serviceAccountName: {{ template "fullname" $root }}
          {{- end }}
          automountServiceAccountToken: false
          {{- if .nodeSelector }}
          nodeSelector:
          {{- range $name, $value := .nodeSelector }}
            {{ $name }}: {{ $value | quote }}
          {{- end }}
          {{- else if $defaults.nodeSelector }}
          nodeSelector:
          {{- range $name, $value := $defaults.nodeSelector }}
            {{ $name }}: {{ $value | quote }}
          {{- end }}
          {{- end }}
          containers:
            - name: {{ template "name" $root }}-{{ $job.name }}
              {{- if .image }}
              image: {{ .image }}
              {{- else }}
              image: {{ $global.registry -}} / {{- $serviceName -}} : {{- $global.build.imageTag }}
              {{- end }}
              imagePullPolicy: {{ $global.imagePullPolicy | quote }}
              securityContext:
                {{- if quote $job.runAsUser }}
                runAsUser: {{ $job.runAsUser }}
                {{- end }}
                {{- if quote $job.runAsGroup }}
                runAsGroup: {{ $job.runAsGroup }}
                {{- end }}
                allowPrivilegeEscalation: false
              {{- if $job.command }}
              command:
                {{- range $job.command }}
                - {{ . }}
                {{- end }}
              {{- end }}
              {{- if $job.args }}
              args:
                {{- range $job.args }}
                - {{ . }}
                {{- end }}
              {{- end }}
              resources:
                requests:
                  cpu: {{ coalesce $job.cpuRequest .cpuRequest $defaults.cpuRequest }}
                  memory: {{ coalesce $job.memoryRequest .memoryRequest $defaults.memoryRequest }}
                limits:
                  cpu: {{ coalesce $job.cpuLimit .cpuLimit $defaults.cpuLimit }}
                  memory: {{ coalesce $job.memoryLimit .memoryLimit $defaults.memoryLimit }}
                  {{- if coalesce $job.gpuLimit .gpuLimit }}
                  nvidia.com/gpu: {{ coalesce $job.gpuLimit .gpuLimit }}
                  {{- end }}
              # TODO: resource requests and limits
              envFrom:
                - prefix: COMMON_
                  configMapRef:
                    name: {{ template "fullname" $root }}-common
              env:
                {{- if and (.serviceAccount) (eq $provider "gcp") }}
                {{- if .serviceAccount.secret }}
                - name: GOOGLE_APPLICATION_CREDENTIALS
                  value: /serviceaccount/{{ regexFind "[a-zA-Z]*$" .serviceAccount.secret }}
                {{- end }}
                {{- end }}
                {{- range $name, $value := $defaults.env }}
                - name: {{ $name }}
                  value: {{ $value | quote }}
                {{- end }}
                {{- range $name, $value := .env }}
                - name: {{ $name }}
                  value: {{ $value | quote }}
                {{- end }}
                {{- range $name, $value := $job.env }}
                - name: {{ $name }}
                  value: {{ $value | quote }}
                {{- end }}
                {{- range $name, $value := $defaults.secretEnv }}
                - name: {{ $name }}
                  valueFrom:
                    secretKeyRef:
                      name: {{ regexReplaceAll "\\.[a-zA-Z]*$" $value "" }}
                      key: {{ regexFind "[a-zA-Z]*$" $value }}
                {{- end }}
                {{- range $name, $value := .secretEnv }}
                - name: {{ $name }}
                  valueFrom:
                    secretKeyRef:
                      name: {{ regexReplaceAll "\\.[a-zA-Z]*$" $value "" }}
                      key: {{ regexFind "[a-zA-Z]*$" $value }}
                {{- end }}
                {{- range $name, $value := $job.secretEnv }}
                - name: {{ $name }}
                  valueFrom:
                    secretKeyRef:
                      name: {{ regexReplaceAll "\\.[a-zA-Z]*$" $value "" }}
                      key: {{ regexFind "[a-zA-Z]*$" $value }}
                {{- end }}
              volumeMounts:
              {{- range $name, $value := $defaults.secrets }}
                - name: default- {{- lower $name | replace "_" "-" }}
                  mountPath: /run/secrets/ {{- $name }}
                  subPath: {{ $name }}
                  readOnly: true
              {{- end }}
              {{- range $name, $value := .secrets }}
                - name: {{ lower $name | replace "_" "-" }}
                  mountPath: /run/secrets/ {{- $name }}
                  subPath: {{ $name }}
                  readOnly: true
              {{- end }}
              {{- range $name, $value := $job.secrets }}
                - name: {{ lower $name | replace "_" "-" }}
                  mountPath: /run/secrets/ {{- $name }}
                  subPath: {{ $name }}
                  readOnly: true
              {{- end }}
              {{- if and (.serviceAccount) (eq $provider "gcp") }}
              {{- if .serviceAccount.secret }}
                - name: serviceaccount
                  mountPath: /serviceaccount
                  readOnly: true
              {{- end }}
              {{- end }}
            {{- if and (.db) (ne $env "local") (eq $provider "gcp") }}
            - name: cloudsql-proxy
              image: gcr.io/cloudsql-docker/gce-proxy:1.17
              command:
                - /cloud_sql_proxy
                - -verbose=false
                - -log_debug_stdout=true
                - --dir=/cloudsql
                - -instances={{ .db.instance }}=tcp:{{ .db.port }}
                - -credential_file=/secrets/cloudsql/{{ regexFind "[a-zA-Z]*$" .db.proxySecret }}
              volumeMounts:
                - name: cloudsql-instance-credentials
                  mountPath: /secrets/cloudsql
                  readOnly: true
                - name: ssl-certs
                  mountPath: /etc/ssl/certs
                - name: cloudsql
                  mountPath: /cloudsql
            {{- end }}
          volumes:
            {{- range $name, $value := $defaults.secrets }}
            - name: default- {{- lower $name | replace "_" "-" }}
              secret:
                secretName: {{ regexReplaceAll "\\.[a-zA-Z]*$" $value "" }}
                items:
                - key: {{ regexFind "[a-zA-Z]*$" $value }}
                  path: {{ $name }}
            {{- end }}
            {{- range $name, $value := .secrets }}
            - name: {{ lower $name | replace "_" "-" }}
              secret:
                secretName: {{ regexReplaceAll "\\.[a-zA-Z]*$" $value "" }}
                items:
                - key: {{ regexFind "[a-zA-Z]*$" $value }}
                  path: {{ $name }}
            {{- end }}
            {{- range $name, $value := $job.secrets }}
            - name: {{ lower $name | replace "_" "-" }}
              secret:
                secretName: {{ regexReplaceAll "\\.[a-zA-Z]*$" $value "" }}
                items:
                - key: {{ regexFind "[a-zA-Z]*$" $value }}
                  path: {{ $name }}
            {{- end }}
            {{- if and (.db) (ne $env "local") (eq $provider "gcp") }}
            - name: cloudsql-instance-credentials
              secret:
                secretName: {{ regexReplaceAll "\\.[a-zA-Z]*$" .db.proxySecret "" }}
            - name: ssl-certs
              hostPath:
                path: /etc/ssl/certs
            - name: cloudsql
              emptyDir:
            {{- end }}
            {{- if and (.serviceAccount) (eq $provider "gcp") }}
            {{- if .serviceAccount.secret }}
            - name: serviceaccount
              secret:
                secretName: {{ regexReplaceAll "\\.[a-zA-Z]*$" .serviceAccount.secret "" }}
            {{- end }}
            {{- end }}
---
{{- end }}
{{- end }}

{{- end }}
{{- end }}
{{- end }}
