{{- $root := . -}}
{{- $env := .Values.global.env -}}
{{- $global := .Values.global -}}
{{- $provider := .Values.global.zone.provider -}}
{{- $defaults := .Values.serviceDefaults -}}

{{- range $serviceName, $service := .Values.services }}
{{- with $service }}
{{- if or (not (hasKey . "enabled")) (.enabled) }}
{{- if not .type }}
{{- if .autoscale }}
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "fullname" $root }}-{{ $serviceName }}
  labels:
    app: {{ template "name" $root }}
    chart: {{ $root.Chart.Name }}-{{ $root.Chart.Version | replace "+" "_" }}
    release: {{ $root.Release.Name }}
    heritage: {{ $root.Release.Service }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "name" $root }}-{{ $serviceName }}
  minReplicas: {{ .minReplicas | default $defaults.minReplicas }}
  maxReplicas: {{ .maxReplicas | default $defaults.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .autoscaleCpuPercentage | default $defaults.autoscaleCpuPercentage }}
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: {{ .autoscaleMemoryPercentage | default $defaults.autoscaleMemoryPercentage }}
---
{{- end }}
{{- if .verticalScaleUpdateMode }}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ template "fullname" $root }}-{{ $serviceName }}
  labels:
    app: {{ template "name" $root }}
    chart: {{ $root.Chart.Name }}-{{ $root.Chart.Version | replace "+" "_" }}
    release: {{ $root.Release.Name }}
    heritage: {{ $root.Release.Service }}
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: {{ template "name" $root }}-{{ $serviceName }}
  updatePolicy:
    updateMode: {{ .verticalScaleUpdateMode }}
---
{{- end }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "fullname" $root }}-{{ $serviceName }}
  labels:
    app: {{ template "name" $root }}
    chart: {{ $root.Chart.Name }}-{{ $root.Chart.Version | replace "+" "_" }}
    release: {{ $root.Release.Name }}
    heritage: {{ $root.Release.Service }}
    {{- range $egress := .egress }}
    {{- if $egress.fullname }}
    access-{{ $egress.fullname }}: "true"
    {{- end }}
    {{- end }}
spec:
  replicas: {{ .replicas | default $defaults.replicas }}
  selector:
    matchLabels:
      app: {{ template "name" $root }}
      release: {{ $root.Release.Name }}
      {{- if default $defaults.tier .tier }}
      tier: {{ default $defaults.tier .tier }}
      {{- end }}
      role: {{ $serviceName }}
  {{- if default $defaults.strategyType .strategyType }}
  strategy:
    type: {{ default $defaults.strategyType .strategyType }}
  {{- end }}
  template:
    metadata:
      labels:
        app: {{ template "name" $root }}
        release: {{ $root.Release.Name }}
        {{- if default $defaults.tier .tier }}
        tier: {{ default $defaults.tier .tier }}
        {{- end }}
        role: {{ $serviceName }}
    spec:
      {{- if $root.Values.serviceAccountCreate }}
      serviceAccountName: {{ template "fullname" $root }}
      {{- end }}
      automountServiceAccountToken: false
      containers:
        - name: {{ template "name" $root }}-{{ $serviceName }}
          {{- if .image }}
          image: {{ .image }}
          {{- else }}
          image: {{ $global.registry -}} / {{- $serviceName -}} : {{- $global.build.imageTag }}
          {{- end }}
          imagePullPolicy: {{ $global.imagePullPolicy | quote }}
          securityContext:
            {{- if .runAsUser }}
            runAsUser: {{ .runAsUser }}
            {{- end }}
            {{- if .runAsGroup }}
            runAsGroup: {{ .runAsGroup }}
            {{- end }}
            privileged: {{ .privileged | default false }}
            allowPrivilegeEscalation: {{ .allowPrivilegeEscalation | default false }}
            capabilities:
              add:
                {{- if .capabilities }}
                {{- range $cab := .capabilities }}
                - {{ $cab }}
                {{- end }}
                {{- end }}
          {{- if .command }}
          command:
            {{- range .command }}
            - {{ . }}
            {{- end }}
          {{- end }}
          ports:
            - containerPort: {{ .port | default $defaults.port }}
          resources:
            requests:
              cpu: {{ .cpuRequest | default $defaults.cpuRequest }}
              memory: {{ .memoryRequest | default $defaults.memoryRequest }}
            limits:
              cpu: {{ .cpuLimit | default $defaults.cpuLimit }}
              memory: {{ .memoryLimit | default $defaults.memoryLimit }}
          {{- if not .livenessDisabled }}
          livenessProbe:
            {{- if .livenessCommand }}
            exec:
              command:
              {{- range .livenessCommand }}
              - {{ . }}
              {{- end }}
            {{- else }}
            httpGet:
              path: {{ coalesce .livenessPath $defaults.livenessPath }}
              port: {{ coalesce .livenessPort .port $defaults.port }}
              scheme: HTTP
            {{- end }}
            initialDelaySeconds: {{ coalesce .livenessInitialDelay $defaults.livenessInitialDelay }}
            periodSeconds: {{ coalesce .livenessPeriod $defaults.livenessPeriod 10 }}
            timeoutSeconds: {{ coalesce .livenessTimeout $defaults.livenessTimeout 3 }}
            failureThreshold: {{ coalesce .livenessFailureThreshold $defaults.livenessFailureThreshold 3 }}
            successThreshold: {{ coalesce .livenessSuccessThreshold $defaults.livenessSuccessThreshold 1 }}
          readinessProbe:
            {{- if .livenessCommand }}
            exec:
              command:
              {{- range .livenessCommand }}
              - {{ . }}
              {{- end }}
            {{- else }}
            httpGet:
              path: {{ coalesce .readinessPath .livenessPath $defaults.livenessPath }}
              port: {{ coalesce .readinessPort .livenessPort .port $defaults.port }}
              scheme: HTTP
            {{- end }}
            initialDelaySeconds: {{ coalesce .readinessInitialDelay $defaults.readinessInitialDelay 30 }}
            periodSeconds: {{ coalesce .readinessPeriod $defaults.readinessPeriod 10 }}
            timeoutSeconds: {{ coalesce .readinessTimeout $defaults.readinessTimeout 3 }}
            failureThreshold: {{ coalesce .readinessFailureThreshold $defaults.readinessFailureThreshold 6 }}
            successThreshold: {{ coalesce .readinessSuccessThreshold $defaults.readinessSuccessThreshold 1 }}
          {{- end }}
          envFrom:
            - prefix: COMMON_
              configMapRef:
                name: {{ template "fullname" $root }}-common
          env:
            {{- if and (.serviceAccount) (eq $provider "gcp") }}
            {{- if .serviceAccount.secret }}
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /serviceaccount/{{ regexFind "[a-zA-Z]*$" .serviceAccount.secret }}
            {{- end }}
            {{- end }}
            {{- range $name, $value := $defaults.env }}
            - name: {{ $name }}
              value: {{ $value | quote }}
            {{- end }}
            {{- range $name, $value := .env }}
            - name: {{ $name }}
              value: {{ $value | quote }}
            {{- end }}
            {{- range $name, $value := $defaults.secretEnv }}
            - name: {{ $name }}
              valueFrom:
                secretKeyRef:
                  name: {{ regexReplaceAll "\\.[a-zA-Z]*$" $value "" }}
                  key: {{ regexFind "[a-zA-Z]*$" $value }}
            {{- end }}
            {{- range $name, $value := .secretEnv }}
            - name: {{ $name }}
              valueFrom:
                secretKeyRef:
                  name: {{ regexReplaceAll "\\.[a-zA-Z]*$" $value "" }}
                  key: {{ regexFind "[a-zA-Z]*$" $value }}
            {{- end }}
          volumeMounts:
          {{- range $name, $value := $defaults.secrets }}
          {{- if $value }}
            - name: default- {{- lower $name | replace "_" "-" }}
              mountPath: /run/secrets/ {{- $name }}
              subPath: {{ $name }}
              readOnly: true
          {{- end }}
          {{- end }}
          {{- range $name, $value := .secrets }}
          {{- if $value }}
            - name: {{ lower $name | replace "_" "-" }}
              mountPath: /run/secrets/ {{- $name }}
              subPath: {{ $name }}
              readOnly: true
          {{- end }}
          {{- end }}
          {{- if .hostDevices }}
          {{- range .hostDevices }}
            - mountPath: {{ .path }}
              name: {{ .name }}
              readOnly: {{ .readOnly }}
          {{- end }}
          {{- end }}
          {{- if .temporaryVolumeMounts }}
          {{- range .temporaryVolumeMounts }}
            - mountPath: {{ .mountPath }}
              name: temporary-volume
              subPath: {{ .volumePath }}
              readOnly: {{ .readOnly }}
          {{- end }}
          {{- end }}
          {{- if $root.Values.persistence.enabled }}
          {{- if .persistentVolumeMounts }}
          {{- range .persistentVolumeMounts }}
            - mountPath: {{ .mountPath }}
              name: persistent-volume
              subPath: {{ .volumePath }}
              readOnly: {{ .readOnly }}
          {{- end }}
          {{- end }}
          {{- end }}
          {{- if .sidecar }}
          {{- if .sidecar.enabled }}
          {{- if .sidecar.sharedVolume }}
            - name: sidecar-volume
              mountPath: {{ .sidecar.sharedVolume.mountPath }}
          {{- end }}
          {{- end }}
          {{- end }}
          {{- if and (.serviceAccount) (eq $provider "gcp") }}
          {{- if .serviceAccount.secret }}
            - name: serviceaccount
              mountPath: /serviceaccount
              readOnly: true
          {{- end }}
          {{- end }}

        {{- if .sidecar }}
        {{- if .sidecar.enabled }}
        - name: {{ template "name" $root }}-{{ .sidecar.name }}
          {{- if .sidecar.image }}
          image: {{ .sidecar.image }}
          {{- else }}
          image: {{ $global.registry -}} / {{- .sidecar.name -}} : {{- $global.build.imageTag }}
          {{- end }}
          imagePullPolicy: {{ $global.imagePullPolicy | quote }}
          securityContext:
            {{- if .sidecar.runAsUser }}
            runAsUser: {{ .sidecar.runAsUser }}
            {{- end }}
            {{- if .sidecar.runAsGroup }}
            runAsGroup: {{ .sidecar.runAsGroup }}
            {{- end }}
            privileged: {{ .sidecar.privileged | default false }}
            allowPrivilegeEscalation: {{ .sidecar.allowPrivilegeEscalation | default false }}
            capabilities:
              add:
                {{- if .sidecar.capabilities }}
                {{- range $cab := .sidecar.capabilities }}
                - {{ $cab }}
                {{- end }}
                {{- end }}
          {{- if .sidecar.command }}
          command:
            {{- range .sidecar.command }}
            - {{ . }}
            {{- end }}
          {{- end }}
          ports:
            - containerPort: {{ .sidecar.port | default $defaults.port }}
          {{- if not .sidecar.livenessDisabled }}
          livenessProbe:
            httpGet:
              path: {{ coalesce .sidecar.livenessPath $defaults.livenessPath }}
              port: {{ coalesce .sidecar.livenessPort .sidecar.port $defaults.port }}
              scheme: HTTP
            initialDelaySeconds: {{ coalesce .sidecar.livenessInitialDelay $defaults.livenessInitialDelay }}
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: {{ coalesce .sidecar.readinessPath .sidecar.livenessPath $defaults.livenessPath }}
              port: {{ coalesce .sidecar.readinessPort .sidecar.livenessPort .sidecar.port $defaults.port }}
              scheme: HTTP
            initialDelaySeconds: {{ coalesce .sidecar.readinessInitialDelay 30 }}
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: {{ coalesce .sidecar.readinessFailureThreshold 6 }}
            successThreshold: 1
          {{- end }}
          envFrom:
            - prefix: COMMON_
              configMapRef:
                name: {{ template "fullname" $root }}-common
          env:
            {{- if and (.sidecar.serviceAccount) (eq $provider "gcp") }}
            {{- if .sidecar.serviceAccount.secret }}
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /serviceaccount/{{ regexFind "[a-zA-Z]*$" .sidecar.serviceAccount.secret }}
            {{- end }}
            {{- end }}
            {{- range $name, $value := .sidecar.env }}
            - name: {{ $name }}
              value: {{ $value | quote }}
            {{- end }}
            {{- range $name, $value := .sidecar.secretEnv }}
            - name: {{ $name }}
              valueFrom:
                secretKeyRef:
                  name: {{ regexReplaceAll "\\.[a-zA-Z]*$" $value "" }}
                  key: {{ regexFind "[a-zA-Z]*$" $value }}
            {{- end }}
          volumeMounts:
          {{- range $name, $value := .sidecar.secrets }}
          {{- if $value }}
            - name: sidecar- {{- lower $name | replace "_" "-" }}
              mountPath: /run/secrets/ {{- $name }}
              subPath: {{ $name }}
              readOnly: true
          {{- end }}
          {{- end }}
          {{- if .sidecar.temporaryVolumeMounts }}
          {{- range .sidecar.temporaryVolumeMounts }}
            - mountPath: {{ .mountPath }}
              name: temporary-volume
              subPath: {{ .volumePath }}
              readOnly: {{ .readOnly }}
          {{- end }}
          {{- end }}
          {{- if $root.Values.persistence.enabled }}
          {{- if .sidecar.persistentVolumeMounts }}
          {{- range .sidecar.persistentVolumeMounts }}
            - mountPath: {{ .mountPath }}
              name: persistent-volume
              subPath: {{ .volumePath }}
              readOnly: {{ .readOnly }}
          {{- end }}
          {{- end }}
          {{- end }}
          {{- if .sidecar.sharedVolume }}
            - name: sidecar-volume
              mountPath: {{ .sidecar.sharedVolume.sidecarMountPath }}
          {{- end }}
          {{- if and (.sidecar.serviceAccount) (eq $provider "gcp") }}
          {{- if .sidecar.serviceAccount.secret }}
            - name: serviceaccount
              mountPath: /serviceaccount
              readOnly: true
          {{- end }}
          {{- end }}
        {{- end }}
        {{- end }}

        {{- if and (.db) (eq $provider "gcp") }}
        {{- if .db.useProxy }}
        - name: cloudsql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.13
          securityContext:
            runAsUser: 2
            runAsGroup: 2
            privileged: false
            allowPrivilegeEscalation: false
          command:
            - /cloud_sql_proxy
            - -verbose=false
            - -log_debug_stdout=true
            - --dir=/cloudsql
            - -instances={{ .db.instance }}=tcp:{{ .db.port }}
            - -credential_file=/secrets/cloudsql/{{ regexFind "[a-zA-Z]*$" .db.proxySecret }}
          volumeMounts:
            - name: cloudsql-instance-credentials
              mountPath: /secrets/cloudsql
              readOnly: true
            - name: ssl-certs
              mountPath: /etc/ssl/certs
            - name: cloudsql
              mountPath: /cloudsql
        {{- end }}
        {{- end }}
      volumes:
        {{- if .hostDevices }}
        {{- range .hostDevices }}
        - hostPath:
            path: {{ .path }}
            type: {{ .type }}
          name: {{ .name }}
        {{- end }}
        {{- end }}
        {{- range $name, $value := $defaults.secrets }}
        {{- if $value }}
        - name: default- {{- lower $name | replace "_" "-" }}
          secret:
            secretName: {{ regexReplaceAll "\\.[a-zA-Z]*$" $value "" }}
            items:
            - key: {{ regexFind "[a-zA-Z]*$" $value }}
              path: {{ $name }}
        {{- end }}
        {{- end }}
        {{- range $name, $value := .secrets }}
        {{- if $value }}
        - name: {{ lower $name | replace "_" "-" }}
          secret:
            secretName: {{ regexReplaceAll "\\.[a-zA-Z]*$" $value "" }}
            items:
            - key: {{ regexFind "[a-zA-Z]*$" $value }}
              path: {{ $name }}
        {{- end }}
        {{- end }}
        {{- if .sidecar }}
        {{- if .sidecar.enabled }}
        {{- range $name, $value := .sidecar.secrets }}
        {{- if $value }}
        - name: sidecar- {{- lower $name | replace "_" "-" }}
          secret:
            secretName: {{ regexReplaceAll "\\.[a-zA-Z]*$" $value "" }}
            items:
            - key: {{ regexFind "[a-zA-Z]*$" $value }}
              path: {{ $name }}
        {{- end }}
        {{- end }}
        {{- end }}
        {{- end }}
        {{- if .temporaryVolumeMounts }}
        - name: temporary-volume
          emptyDir:
        {{- end }}
        {{- if $root.Values.persistence.enabled }}
        {{- if .persistentVolumeMounts }}
        - name: persistent-volume
          persistentVolumeClaim:
            claimName: {{ $root.Values.persistence.existingClaim | default (include "fullname" $root) }}
        {{- end }}
        {{- end }}
        {{- if .sidecar }}
        {{- if .sidecar.enabled }}
        {{- if .sidecar.sharedVolume }}
        - name: sidecar-volume
          emptyDir:
        {{- end }}
        {{- end }}
        {{- end }}
        {{- if and (.db) (eq $provider "gcp") }}
        {{- if .db.useProxy }}
        - name: cloudsql-instance-credentials
          secret:
            secretName: {{ regexReplaceAll "\\.[a-zA-Z]*$" .db.proxySecret "" }}
        - name: ssl-certs
          hostPath:
            path: /etc/ssl/certs
        - name: cloudsql
          emptyDir:
        {{- end }}
        {{- end }}
        {{- if and (.serviceAccount) (eq $provider "gcp") }}
        {{- if .serviceAccount.secret }}
        - name: serviceaccount
          secret:
            secretName: {{ regexReplaceAll "\\.[a-zA-Z]*$" .serviceAccount.secret "" }}
        {{- end }}
        {{- end }}
---
{{- end }}
{{- end }}
{{- end }}
{{- end }}
