{{- $root := . -}}
{{- $defaults := .Values.serviceDefaults -}}

# Alternate domain ingresses (redirect)
{{- range $domain := .Values.ingress.domains }}
{{- if $domain.altName }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "fullname" $root }}-ingress-alt
  labels:
    app: {{ template "name" $root }}
    chart: {{ $root.Chart.Name }}-{{ $root.Chart.Version | replace "+" "_" }}
    release: {{ $root.Release.Name }}
    heritage: {{ $root.Release.Service }}
  annotations:
    kubernetes.io/ingress.class: {{ $root.Values.ingress.class | quote }}
    {{- if not $root.Values.ingress.tls }}
    ingress.kubernetes.io/permanent-redirect: http://{{ $domain.name }}
    {{- end }}
    {{- if $root.Values.ingress.tls }}
    kubernetes.io/tls-acme: "true"
    ingress.kubernetes.io/ssl-redirect: "false"
    ingress.kubernetes.io/permanent-redirect: https://{{ $domain.name }}
    {{- end }}
spec:
  {{- if $root.Values.ingress.tls }}
  tls:
  - hosts:
    - {{ $domain.altName }}
    {{- if not $domain.certSecret }}
    secretName: {{ template "fullname" $root }}-ssl
    {{- end }}
    {{- if $domain.certSecret }}
    secretName: {{ $domain.certSecret }}
    {{- end }}
  {{- end }}
  rules:
    - host: {{ $domain.altName }}
---
{{- end }}
{{- end }}

# Master ingress
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "fullname" . }}-ingress
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    nginx.org/mergeable-ingress-type: "master"
    kubernetes.io/ingress.class: {{ .Values.ingress.class | quote }}
    {{- if .Values.ingress.tls }}
    kubernetes.io/tls-acme: "true"
    ingress.kubernetes.io/ssl-redirect: "true"
    ingress.kubernetes.io/force-ssl-redirect: "true"
    {{- end }}
spec:
  {{- if .Values.ingress.tls }}
  tls:
  {{- range $domain := .Values.ingress.domains }}
  - hosts:
    - {{ $domain.name }}
    {{- if not $domain.certSecret }}
    secretName: {{ template "fullname" $root }}-ssl
    {{- end }}
    {{- if $domain.certSecret }}
    secretName: {{ $domain.certSecret }}
    {{- end }}
  {{- end }}
  {{- end }}
  rules:
    {{- range $domain := .Values.ingress.domains }}
    - host: {{ $domain.name }}
    {{- end }}
---


# Service ingresses
{{- range $serviceName, $service := .Values.services }}
{{- if or (not (hasKey $service "enabled")) ($service.enabled) }}


# Minion ingress for each service path
{{- range $path := $service.paths }}
{{- with $path }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "fullname" $root }}-ingress-{{ $serviceName }}{{ .path | default "-root" | replace "/" "-" }}
  labels:
    app: {{ template "name" $root }}
    chart: {{ $root.Chart.Name }}-{{ $root.Chart.Version | replace "+" "_" }}
    release: {{ $root.Release.Name }}
    heritage: {{ $root.Release.Service }}
  annotations:
    nginx.org/mergeable-ingress-type: "minion"
    kubernetes.io/ingress.class: {{ $root.Values.ingress.class | quote }}
    {{- if hasKey . "basicAuthEnabled" | ternary .basicAuthEnabled $defaults.basicAuthEnabled }}
    ingress.kubernetes.io/auth-type: "basic"
    ingress.kubernetes.io/auth-realm: {{ template "name" $root }}
    ingress.kubernetes.io/auth-secret: {{ .basicAuthHtpasswdSecret | default $defaults.basicAuthHtpasswdSecret }}
    {{- end }}
    {{- if not .rewriteTargetDisabled }}
    ingress.kubernetes.io/rewrite-target: {{ default ($root.Values.ingress.oldRewritePolicy | ternary "/" "/$1") .rewriteTarget }}
    {{- end }}
    {{- if .clientMaxBodySize | default $defaults.clientMaxBodySize }}
    ingress.kubernetes.io/proxy-body-size: {{ .clientMaxBodySize | default $defaults.clientMaxBodySize | quote }}
    {{- end }}
    {{- if .bufferSize | default $defaults.bufferSize }}
    ingress.kubernetes.io/proxy-buffer-size: {{ .bufferSize | default $defaults.bufferSize | quote }}
    {{- end }}
    {{- if .requestBuffering | default $defaults.requestBuffering }}
    ingress.kubernetes.io/proxy-request-buffering: {{ .requestBuffering | default $defaults.requestBuffering | quote }}
    {{- end }}
    {{- if .connectTimeout | default $defaults.connectTimeout }}
    ingress.kubernetes.io/proxy-connect-timeout: {{ .connectTimeout | default $defaults.connectTimeout | quote }}
    {{- end }}
    {{- if .sendTimeout | default $defaults.sendTimeout }}
    ingress.kubernetes.io/proxy-send-timeout: {{ .sendTimeout | default $defaults.sendTimeout | quote }}
    {{- end }}
    {{- if .readTimeout | default $defaults.readTimeout }}
    ingress.kubernetes.io/proxy-read-timeout: {{ .readTimeout | default $defaults.readTimeout | quote }}
    {{- end }}
    {{- if .nextUpstreamTimeout | default $defaults.nextUpstreamTimeout }}
    ingress.kubernetes.io/proxy-next-upstream-timeout: {{ .nextUpstreamTimeout | default $defaults.nextUpstreamTimeout | quote }}
    {{- end }}
    {{- if .limitRate | default $defaults.limitRate }}
    ingress.kubernetes.io/limit-rate: {{ .limitRate | default $defaults.limitRate | quote }}
    {{- end }}
    {{- if .limitRateAfter | default $defaults.limitRateAfter }}
    ingress.kubernetes.io/limit-rate-after: {{ .limitRateAfter | default $defaults.limitRateAfter | quote }}
    {{- end }}
spec:
  rules:
    {{- range $domain := $root.Values.ingress.domains }}
    - host: {{ $domain.name }}
      http:
        paths:
          {{- if or .rewriteTargetDisabled .rewriteTarget }}
          - path: {{ $path.path }}
          {{- else }}
          - path: {{ $path.path }}{{ $root.Values.ingress.oldRewritePolicy | ternary "" "/?(.*)" }}
          {{- end }}
            backend:
              serviceName: {{ template "fullname" $root }}-{{ $serviceName }}
              servicePort: {{ $service.port | default $defaults.port }}
    {{- end }}
---
{{- end }}
{{- end }}


# Minion ingress for each service sidecar path
# TODO: duplicate code with 'minion ingress for each service path'
{{- if $service.sidecar }}
{{- if $service.sidecar.enabled }}
{{- range $path := $service.sidecar.paths }}
{{- with $path }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "fullname" $root }}-ingress-{{ $serviceName }}-sidecar{{ .path | default "-root" | replace "/" "-" }}
  labels:
    app: {{ template "name" $root }}
    chart: {{ $root.Chart.Name }}-{{ $root.Chart.Version | replace "+" "_" }}
    release: {{ $root.Release.Name }}
    heritage: {{ $root.Release.Service }}
  annotations:
    nginx.org/mergeable-ingress-type: "minion"
    kubernetes.io/ingress.class: {{ $root.Values.ingress.class | quote }}
    {{- if hasKey . "basicAuthEnabled" | ternary .basicAuthEnabled $defaults.basicAuthEnabled }}
    ingress.kubernetes.io/auth-type: "basic"
    ingress.kubernetes.io/auth-realm: {{ template "name" $root }}
    ingress.kubernetes.io/auth-secret: {{ .basicAuthHtpasswdSecret | default $defaults.basicAuthHtpasswdSecret }}
    {{- end }}
    {{- if not .rewriteTargetDisabled }}
    ingress.kubernetes.io/rewrite-target: {{ default ($root.Values.ingress.oldRewritePolicy | ternary "/" "/$1") .rewriteTarget }}
    {{- end }}
    {{- if .clientMaxBodySize | default $defaults.clientMaxBodySize }}
    ingress.kubernetes.io/proxy-body-size: {{ .clientMaxBodySize | default $defaults.clientMaxBodySize | quote }}
    {{- end }}
    {{- if .bufferSize | default $defaults.bufferSize }}
    ingress.kubernetes.io/proxy-buffer-size: {{ .bufferSize | default $defaults.bufferSize | quote }}
    {{- end }}
    {{- if .requestBuffering | default $defaults.requestBuffering }}
    ingress.kubernetes.io/proxy-request-buffering: {{ .requestBuffering | default $defaults.requestBuffering | quote }}
    {{- end }}
    {{- if .connectTimeout | default $defaults.connectTimeout }}
    ingress.kubernetes.io/proxy-connect-timeout: {{ .connectTimeout | default $defaults.connectTimeout | quote }}
    {{- end }}
    {{- if .sendTimeout | default $defaults.sendTimeout }}
    ingress.kubernetes.io/proxy-send-timeout: {{ .sendTimeout | default $defaults.sendTimeout | quote }}
    {{- end }}
    {{- if .readTimeout | default $defaults.readTimeout }}
    ingress.kubernetes.io/proxy-read-timeout: {{ .readTimeout | default $defaults.readTimeout | quote }}
    {{- end }}
    {{- if .nextUpstreamTimeout | default $defaults.nextUpstreamTimeout }}
    ingress.kubernetes.io/proxy-next-upstream-timeout: {{ .nextUpstreamTimeout | default $defaults.nextUpstreamTimeout | quote }}
    {{- end }}
    {{- if .limitRate | default $defaults.limitRate }}
    ingress.kubernetes.io/limit-rate: {{ .limitRate | default $defaults.limitRate | quote }}
    {{- end }}
    {{- if .limitRateAfter | default $defaults.limitRateAfter }}
    ingress.kubernetes.io/limit-rate-after: {{ .limitRateAfter | default $defaults.limitRateAfter | quote }}
    {{- end }}
spec:
  rules:
    {{- range $domain := $root.Values.ingress.domains }}
    - host: {{ $domain.name }}
      http:
        paths:
          {{- if or .rewriteTargetDisabled .rewriteTarget }}
          - path: {{ $path.path }}
          {{- else }}
          - path: {{ $path.path }}{{ $root.Values.ingress.oldRewritePolicy | ternary "" "/?(.*)" }}
          {{- end }}
            backend:
              serviceName: {{ template "fullname" $root }}-{{ $serviceName }}
              servicePort: {{ $service.sidecar.port | default $defaults.port }}
    {{- end }}
---
{{- end }}
{{- end }}
{{- end }}
{{- end }}



{{- end }}
{{- end }}
