{{- $root := . -}}
{{- $defaults := .Values.serviceDefaults -}}

# Master ingress
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "fullname" . }}-ingress
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    nginx.org/mergeable-ingress-type: "master"
    kubernetes.io/ingress.class: {{ .Values.ingress.class | quote }}
    # TODO: some of these need to set for minions?
    ingress.kubernetes.io/proxy-body-size: {{ .Values.ingress.maxBodySize | quote }}
    {{- if .limitRate }}
    ingress.kubernetes.io/limit-rate: {{ .Values.ingress.limitRate | quote }}
    {{- end }}
    {{- if .limitRateAfter }}
    ingress.kubernetes.io/limit-rate-after: {{ .Values.ingress.limitRateAfter | quote }}
    {{- end }}
    {{- if .Values.ingress.basicAuth.enabled }}
    ingress.kubernetes.io/auth-type: "basic"
    ingress.kubernetes.io/auth-realm: {{ template "name" . }}
    ingress.kubernetes.io/auth-secret: {{ .Values.ingress.basicAuth.htpasswdSecret }}
    {{- end }}
    {{- if .Values.ingress.tls }}
    kubernetes.io/tls-acme: "true"
    ingress.kubernetes.io/ssl-redirect: "true"
    ingress.kubernetes.io/force-ssl-redirect: "true"
    {{- end }}
    # NOTE: see https://github.com/kubernetes/ingress/blob/master/controllers/nginx/configuration.md
    # TODO ingress.kubernetes.io/limit-connections
    # TODO ingress.kubernetes.io/limit-rps
spec:
  {{- if .Values.ingress.tls }}
  tls:
  {{- range $domain := .Values.ingress.domains }}
  - hosts:
    - {{ $domain.name }}
    {{- if not $domain.certSecret }}
    secretName: {{ template "fullname" $root }}-ssl
    {{- end }}
    {{- if $domain.certSecret }}
    secretName: {{ $domain.certSecret }}
    {{- end }}
  {{- end }}
  {{- end }}
  rules:
    {{- range $domain := .Values.ingress.domains }}
    - host: {{ $domain.name }}
    {{- end }}


# Service ingresses
{{- range $serviceName, $service := .Values.services }}
{{- if or (not (hasKey $service "enabled")) ($service.enabled) }}


# Minion ingress for each service path
{{- range $path := $service.paths }}
{{- with $path }}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "fullname" $root }}-ingress-{{ $serviceName }}{{ .path | default "-root" | replace "/" "-" }}
  labels:
    app: {{ template "name" $root }}
    chart: {{ $root.Chart.Name }}-{{ $root.Chart.Version | replace "+" "_" }}
    release: {{ $root.Release.Name }}
    heritage: {{ $root.Release.Service }}
  annotations:
    nginx.org/mergeable-ingress-type: "minion"
    kubernetes.io/ingress.class: {{ $root.Values.ingress.class | quote }}
    {{- if $root.Values.ingress.basicAuth.enabled }}
    ingress.kubernetes.io/auth-type: "basic"
    ingress.kubernetes.io/auth-realm: {{ template "name" $root }}
    ingress.kubernetes.io/auth-secret: {{ $root.Values.ingress.basicAuth.htpasswdSecret }}
    {{- end }}
    {{- if not .rewriteTargetDisabled }}
    ingress.kubernetes.io/rewrite-target: {{ default .rewriteTarget ($root.Values.ingress.oldRewritePolicy | ternary "/" "/$1") }}
    {{- end }}
    {{- if .maxBodySize }}
    ingress.kubernetes.io/proxy-body-size: {{ .maxBodySize | quote }}
    {{- end }}
    {{- if .limitRate }}
    ingress.kubernetes.io/limit-rate: {{ .limitRate | quote }}
    {{- end }}
    {{- if .limitRateAfter }}
    ingress.kubernetes.io/limit-rate-after: {{ .limitRateAfter | quote }}
    {{- end }}
spec:
  rules:
    {{- range $domain := $root.Values.ingress.domains }}
    - host: {{ $domain.name }}
      http:
        paths:
          {{- if or .rewriteTargetDisabled .rewriteTarget }}
          - path: {{ $path.path }}
          {{- else }}
          - path: {{ $path.path }}{{ $root.Values.ingress.oldRewritePolicy | ternary "" "/?(.*)" }}
          {{- end }}
            backend:
              serviceName: {{ template "fullname" $root }}-{{ $serviceName }}
              servicePort: {{ $service.port | default $defaults.port }}
    {{- end }}
{{- end }}
{{- end }}


# Minion ingress for each service sidecar path
# TODO: duplicate code with 'minion ingress for each service path'
{{- if $service.sidecar }}
{{- if $service.sidecar.enabled }}
{{- range $path := $service.sidecar.paths }}
{{- with $path }}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "fullname" $root }}-ingress-{{ $serviceName }}-sidecar{{ .path | default "-root" | replace "/" "-" }}
  labels:
    app: {{ template "name" $root }}
    chart: {{ $root.Chart.Name }}-{{ $root.Chart.Version | replace "+" "_" }}
    release: {{ $root.Release.Name }}
    heritage: {{ $root.Release.Service }}
  annotations:
    nginx.org/mergeable-ingress-type: "minion"
    kubernetes.io/ingress.class: {{ $root.Values.ingress.class | quote }}
    {{- if $root.Values.ingress.basicAuth.enabled }}
    ingress.kubernetes.io/auth-type: "basic"
    ingress.kubernetes.io/auth-realm: {{ template "name" $root }}
    ingress.kubernetes.io/auth-secret: {{ $root.Values.ingress.basicAuth.htpasswdSecret }}
    {{- end }}
    {{- if not .rewriteTargetDisabled }}
    ingress.kubernetes.io/rewrite-target: {{ default .rewriteTarget ($root.Values.ingress.oldRewritePolicy | ternary "/" "/$1") }}
    {{- end }}
    {{- if .maxBodySize }}
    ingress.kubernetes.io/proxy-body-size: {{ .maxBodySize | quote }}
    {{- end }}
    {{- if .limitRate }}
    ingress.kubernetes.io/limit-rate: {{ .limitRate | quote }}
    {{- end }}
    {{- if .limitRateAfter }}
    ingress.kubernetes.io/limit-rate-after: {{ .limitRateAfter | quote }}
    {{- end }}
spec:
  rules:
    {{- range $domain := $root.Values.ingress.domains }}
    - host: {{ $domain.name }}
      http:
        paths:
          {{- if or .rewriteTargetDisabled .rewriteTarget }}
          - path: {{ $path.path }}
          {{- else }}
          - path: {{ $path.path }}{{ $root.Values.ingress.oldRewritePolicy | ternary "" "/?(.*)" }}
          {{- end }}
            backend:
              serviceName: {{ template "fullname" $root }}-{{ $serviceName }}
              servicePort: {{ $service.sidecar.port | default $defaults.port }}
    {{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}



{{- end }}
{{- end }}
