{{- $root := . -}}
{{- $defaults := .Values.serviceDefaults -}}
{{- $annoPrefix := .Values.ingress.oldRewritePolicy | ternary "" "nginx." -}}

{{- if or (not (hasKey $root.Values.ingress "enabled")) ($root.Values.ingress.enabled) }}
{{- if not (contains "openshift" $root.Values.ingress.class) }}

# Alternate domain ingresses (redirect)
# TODO: add non-nginx support
{{- if contains "nginx" $root.Values.ingress.class }}
{{- range $domain := .Values.ingress.domains }}
{{- if $domain.altDomains }}

# TODO: temporary fix for Helm v2 backwards compatibility
# -> for Helm v3 was: if (get (first $domain.altDomains) "name")
{{- $altDomainSettings := dict "enabled" false -}}
{{- range $altDomain := $domain.altDomains }}
{{- if $altDomain.name }}
{{- $altDomainSettings := set $altDomainSettings "enabled" true -}}
{{- end }}
{{- end }}

{{- if $altDomainSettings.enabled }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ template "fullname" $root }}-ingress-alt
  annotations:
    {{- if $root.Values.ingress.class }}
    kubernetes.io/ingress.class: {{ $root.Values.ingress.class | quote }}
    {{- end }}
    {{- if not $root.Values.ingress.tls }}
    {{ $annoPrefix }}ingress.kubernetes.io/server-snippet: |
      if ($request_uri !~ ^/\.well-known/.*$) {
        return 301 http://{{ $domain.name }}$request_uri;
      }
    {{- end }}
    {{- if $root.Values.ingress.tls }}
    kubernetes.io/tls-acme: "true"
    {{ $annoPrefix }}ingress.kubernetes.io/ssl-redirect: "false"
    {{ $annoPrefix }}ingress.kubernetes.io/server-snippet: |
      if ($request_uri !~ ^/\.well-known/.*$) {
        return 301 https://{{ $domain.name }}$request_uri;
      }
    {{- end }}
    {{- if $domain.annotations }}
    {{- range $annotationName, $annotationValue := $domain.annotations }}
    {{ $annotationName }}: {{ $annotationValue }}
    {{- end }}
    {{- end }}
spec:
  {{- if $root.Values.ingress.tls }}
  tls:
  - hosts:
    {{- range $altDomain := $domain.altDomains }}
    - {{ $altDomain.name }}
    {{- end }}
    secretName: {{ template "fullname" $root }}-ssl
  {{- end }}
  rules:
    {{- range $altDomain := $domain.altDomains }}
    - host: {{ $altDomain.name }}
      http:
        paths:
          - path: /
            backend:
              # TODO: Remove hardcoded default backend name
              serviceName: common-nginx-nginx-ingress-default-backend
              servicePort: 80
    {{- end }}
---
{{- end }}
{{- end }}
{{- end }}
{{- end }}

# Master ingress
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ template "fullname" . }}-ingress
  annotations:
    {{- if .Values.ingress.class }}
    kubernetes.io/ingress.class: {{ .Values.ingress.class | quote }}
    {{- end }}
    {{- if .Values.ingress.tls }}
    kubernetes.io/tls-acme: "true"
    {{ $annoPrefix }}ingress.kubernetes.io/ssl-redirect: "true"
    {{ $annoPrefix }}ingress.kubernetes.io/force-ssl-redirect: "true"
    {{- end }}
    {{- if .Values.ingress.annotations }}
    {{- range $annotationName, $annotationValue := .Values.ingress.annotations }}
    {{ $annotationName }}: {{ $annotationValue }}
    {{- end }}
    {{- end }}
    {{ $annoPrefix }}ingress.kubernetes.io/server-snippet: |
      location ~ /\.(?!well-known).* {
        deny all;
        access_log off;
        log_not_found off;
        return 404;
      }
spec:
  {{- if .Values.ingress.tls }}
  tls:
  {{- range $domain := .Values.ingress.domains }}
  - hosts:
    - {{ $domain.name }}
    {{- if not $domain.certSecret }}
    secretName: {{ template "fullname" $root }}-ssl
    {{- end }}
    {{- if $domain.certSecret }}
    secretName: {{ $domain.certSecret }}
    {{- end }}
  {{- end }}
  {{- end }}
  rules:
    {{- range $domain := .Values.ingress.domains }}
    - host: {{ $domain.name }}
      # Include service paths on master ingress for non-nginx ingresses
      # -> subpath specific settings not supported for non-nginx ingresses
      {{- if not (contains "nginx" $root.Values.ingress.class) }}
      http:
        paths:
          {{- range $serviceName, $service := $root.Values.services }}
          {{- if or (not (hasKey $service "enabled")) ($service.enabled) }}
          {{- range $path := $service.paths }}
          {{- with $path }}
          - path: {{ default "/" $path.path }}
            backend:
              serviceName: {{ template "fullname" $root }}-{{ $serviceName }}
              servicePort: {{ $service.port | default $defaults.port }}
          {{- end }}
          {{- end }}
          {{- end }}
          {{- end }}
      {{- end }}

    {{- end }}
---

{{- if contains "nginx" $root.Values.ingress.class }}

# Service ingresses
{{- range $serviceName, $service := .Values.services }}
{{- if or (not (hasKey $service "enabled")) ($service.enabled) }}


# Minion ingress for each service path
{{- range $path := $service.paths }}
{{- with $path }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ template "fullname" $root }}-ingress-{{ $serviceName }}{{ .path | default "-root" | replace "/" "-" }}
  annotations:
    {{ $annoPrefix }}ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "Content-Security-Policy: frame-ancestors 'none'";
      more_set_headers "X-Content-Type-Options: nosniff";
      more_set_headers "Referrer-Policy: strict-origin-when-cross-origin";
    {{- if $root.Values.ingress.class }}
    kubernetes.io/ingress.class: {{ $root.Values.ingress.class | quote }}
    {{- end }}
    {{- if hasKey . "basicAuthEnabled" | ternary .basicAuthEnabled $defaults.basicAuthEnabled }}
    {{ $annoPrefix }}ingress.kubernetes.io/auth-type: "basic"
    {{ $annoPrefix }}ingress.kubernetes.io/auth-realm: {{ template "name" $root }}
    {{ $annoPrefix }}ingress.kubernetes.io/auth-secret: {{ .basicAuthHtpasswdSecret | default $defaults.basicAuthHtpasswdSecret }}
    {{- end }}
    {{- if not .rewriteTargetDisabled }}
    # TODO: remove oldRewritePolicy --> {{ $annoPrefix }}ingress.kubernetes.io/rewrite-target: {{ default "/$1" .rewriteTarget }}
    {{ $annoPrefix }}ingress.kubernetes.io/rewrite-target: {{ default ($root.Values.ingress.oldRewritePolicy | ternary "/" "/$1") .rewriteTarget }}
    {{- end }}
    {{- if .clientMaxBodySize | default $defaults.clientMaxBodySize }}
    {{ $annoPrefix }}ingress.kubernetes.io/proxy-body-size: {{ .clientMaxBodySize | default $defaults.clientMaxBodySize | quote }}
    {{- end }}
    {{- if .bufferSize | default $defaults.bufferSize }}
    {{ $annoPrefix }}ingress.kubernetes.io/proxy-buffer-size: {{ .bufferSize | default $defaults.bufferSize | quote }}
    {{- end }}
    {{- if .requestBuffering | default $defaults.requestBuffering }}
    {{ $annoPrefix }}ingress.kubernetes.io/proxy-request-buffering: {{ .requestBuffering | default $defaults.requestBuffering | quote }}
    {{- end }}
    {{- if .connectTimeout | default $defaults.connectTimeout }}
    {{ $annoPrefix }}ingress.kubernetes.io/proxy-connect-timeout: {{ .connectTimeout | default $defaults.connectTimeout | quote }}
    {{- end }}
    {{- if .sendTimeout | default $defaults.sendTimeout }}
    {{ $annoPrefix }}ingress.kubernetes.io/proxy-send-timeout: {{ .sendTimeout | default $defaults.sendTimeout | quote }}
    {{- end }}
    {{- if .readTimeout | default $defaults.readTimeout }}
    {{ $annoPrefix }}ingress.kubernetes.io/proxy-read-timeout: {{ .readTimeout | default $defaults.readTimeout | quote }}
    {{- end }}
    {{- if .nextUpstreamTimeout | default $defaults.nextUpstreamTimeout }}
    {{ $annoPrefix }}ingress.kubernetes.io/proxy-next-upstream-timeout: {{ .nextUpstreamTimeout | default $defaults.nextUpstreamTimeout | quote }}
    {{- end }}
    {{- if .limitConnections | default $defaults.limitConnections }}
    {{ $annoPrefix }}ingress.kubernetes.io/limit-connections: {{ .limitConnections | default $defaults.limitConnections | quote }}
    {{- end }}
    {{- if .limitRpm | default $defaults.limitRpm }}
    {{ $annoPrefix }}ingress.kubernetes.io/limit-rpm: {{ .limitRpm | default $defaults.limitRpm | quote }}
    {{- end }}
    {{- if .limitRate | default $defaults.limitRate }}
    {{ $annoPrefix }}ingress.kubernetes.io/limit-rate: {{ .limitRate | default $defaults.limitRate | quote }}
    {{- end }}
    {{- if .limitRateAfter | default $defaults.limitRateAfter }}
    {{ $annoPrefix }}ingress.kubernetes.io/limit-rate-after: {{ .limitRateAfter | default $defaults.limitRateAfter | quote }}
    {{- end }}
    {{- if coalesce .limitRate $defaults.limitRate .limitRateAfter $defaults.limitRateAfter }}
    {{ $annoPrefix }}ingress.kubernetes.io/proxy-buffering: "on"
    {{- end }}
    {{- $limitWhitelistCidrs := .limitWhitelistCidrs | default $defaults.limitWhitelistCidrs }}
    {{- if $limitWhitelistCidrs }}
    {{ $annoPrefix }}ingress.kubernetes.io/limit-whitelist: |
      {{ range $limitWhitelistCidrs }}{{ . }},{{ end }}127.0.0.1/32
    {{- end }}
    {{- if .modsecurityEnabled | default $defaults.modsecurityEnabled }}
    {{ $annoPrefix }}ingress.kubernetes.io/enable-modsecurity: "true"
    {{ $annoPrefix }}ingress.kubernetes.io/modsecurity-transaction-id: "$request_id"
    {{- if .modsecurityRules | default $defaults.modsecurityRules }}
    {{ $annoPrefix }}ingress.kubernetes.io/enable-owasp-core-rules: "false"
    {{ $annoPrefix }}ingress.kubernetes.io/modsecurity-snippet: {{ .modsecurityRules | default $defaults.modsecurityRules }}
    {{- else }}
    {{ $annoPrefix }}ingress.kubernetes.io/enable-owasp-core-rules: "true"
    {{- end }}
    {{- else }}
    {{ $annoPrefix }}ingress.kubernetes.io/enable-modsecurity: "false"
    {{ $annoPrefix }}ingress.kubernetes.io/enable-owasp-core-rules: "false"
    {{- end }}
    {{- if .allowedCountries | default $defaults.allowedCountries }}
    {{ $annoPrefix }}ingress.kubernetes.io/server-snippet: |
      map $geoip2_city_country_code $allowed_country {
        default no;
        {{- range .allowedCountries | default $defaults.allowedCountries }}
        {{ . }} yes;
        {{- end }}
      }
    {{ $annoPrefix }}ingress.kubernetes.io/configuration-snippet: |
      if ($allowed_country = no) {
        return 444;
      }
    {{- else if .blockedCountries | default $defaults.blockedCountries }}
    {{ $annoPrefix }}ingress.kubernetes.io/server-snippet: |
      map $geoip2_city_country_code $blocked_country {
        default yes;
        {{- range .blockedCountries | default $defaults.blockedCountries }}
        {{ . }} no;
        {{- end }}
      }
    {{ $annoPrefix }}ingress.kubernetes.io/configuration-snippet: |
      if ($blocked_country) {
        return 444;
      }
    {{- end }}
    {{- $cidrs := .allowedCidrs | default $defaults.allowedCidrs }}
    {{- if $cidrs }}
    {{ $annoPrefix }}ingress.kubernetes.io/whitelist-source-range: |
      {{ range $i, $cidr := $cidrs }}{{ $cidr }},{{ end }}127.0.0.1/32
    {{- end }}
    {{- if .annotations }}
    {{- range $annotationName, $annotationValue := .annotations }}
    {{ $annotationName }}: {{ $annotationValue }}
    {{- end }}
    {{- end }}
spec:
  rules:
    {{- range $domain := $root.Values.ingress.domains }}
    - host: {{ $domain.name }}
      http:
        paths:
          {{- if or .rewriteTargetDisabled .rewriteTarget }}
          - path: {{ $path.path }}
          {{- else }}
          # TODO: remove oldRewritePolicy --> - path: {{ $path.path }}{{ "/?(.*)" }}
          - path: {{ $path.path }}{{ $root.Values.ingress.oldRewritePolicy | ternary "" "/?(.*)" }}
          {{- end }}
            backend:
              serviceName: {{ template "fullname" $root }}-{{ $serviceName }}
              servicePort: {{ $service.port | default $defaults.port }}
    {{- end }}
---
{{- end }}
{{- end }}


# Minion ingress for each service sidecar path
# TODO: duplicate code with 'minion ingress for each service path'
{{- if $service.sidecar }}
{{- if $service.sidecar.enabled }}
{{- range $path := $service.sidecar.paths }}
{{- with $path }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ template "fullname" $root }}-ingress-{{ $serviceName }}-sidecar{{ .path | default "-root" | replace "/" "-" }}
  annotations:
    {{ $annoPrefix }}ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "Content-Security-Policy: frame-ancestors 'none'";
      more_set_headers "X-Content-Type-Options: nosniff";
      more_set_headers "Referrer-Policy: strict-origin-when-cross-origin";
    {{- if $root.Values.ingress.class }}
    kubernetes.io/ingress.class: {{ $root.Values.ingress.class | quote }}
    {{- end }}
    {{- if hasKey . "basicAuthEnabled" | ternary .basicAuthEnabled $defaults.basicAuthEnabled }}
    {{ $annoPrefix }}ingress.kubernetes.io/auth-type: "basic"
    {{ $annoPrefix }}ingress.kubernetes.io/auth-realm: {{ template "name" $root }}
    {{ $annoPrefix }}ingress.kubernetes.io/auth-secret: {{ .basicAuthHtpasswdSecret | default $defaults.basicAuthHtpasswdSecret }}
    {{- end }}
    {{- if not .rewriteTargetDisabled }}
    # TODO: remove oldRewritePolicy --> {{ $annoPrefix }}ingress.kubernetes.io/rewrite-target: {{ default "/$1" .rewriteTarget }}
    {{ $annoPrefix }}ingress.kubernetes.io/rewrite-target: {{ default ($root.Values.ingress.oldRewritePolicy | ternary "/" "/$1") .rewriteTarget }}
    {{- end }}
    {{- if .clientMaxBodySize | default $defaults.clientMaxBodySize }}
    {{ $annoPrefix }}ingress.kubernetes.io/proxy-body-size: {{ .clientMaxBodySize | default $defaults.clientMaxBodySize | quote }}
    {{- end }}
    {{- if .bufferSize | default $defaults.bufferSize }}
    {{ $annoPrefix }}ingress.kubernetes.io/proxy-buffer-size: {{ .bufferSize | default $defaults.bufferSize | quote }}
    {{- end }}
    {{- if .requestBuffering | default $defaults.requestBuffering }}
    {{ $annoPrefix }}ingress.kubernetes.io/proxy-request-buffering: {{ .requestBuffering | default $defaults.requestBuffering | quote }}
    {{- end }}
    {{- if .connectTimeout | default $defaults.connectTimeout }}
    {{ $annoPrefix }}ingress.kubernetes.io/proxy-connect-timeout: {{ .connectTimeout | default $defaults.connectTimeout | quote }}
    {{- end }}
    {{- if .sendTimeout | default $defaults.sendTimeout }}
    {{ $annoPrefix }}ingress.kubernetes.io/proxy-send-timeout: {{ .sendTimeout | default $defaults.sendTimeout | quote }}
    {{- end }}
    {{- if .readTimeout | default $defaults.readTimeout }}
    {{ $annoPrefix }}ingress.kubernetes.io/proxy-read-timeout: {{ .readTimeout | default $defaults.readTimeout | quote }}
    {{- end }}
    {{- if .nextUpstreamTimeout | default $defaults.nextUpstreamTimeout }}
    {{ $annoPrefix }}ingress.kubernetes.io/proxy-next-upstream-timeout: {{ .nextUpstreamTimeout | default $defaults.nextUpstreamTimeout | quote }}
    {{- end }}
    {{- if .limitConnections | default $defaults.limitConnections }}
    {{ $annoPrefix }}ingress.kubernetes.io/limit-connections: {{ .limitConnections | default $defaults.limitConnections | quote }}
    {{- end }}
    {{- if .limitRpm | default $defaults.limitRpm }}
    {{ $annoPrefix }}ingress.kubernetes.io/limit-rpm: {{ .limitRpm | default $defaults.limitRpm | quote }}
    {{- end }}
    {{- if .limitRate | default $defaults.limitRate }}
    {{ $annoPrefix }}ingress.kubernetes.io/limit-rate: {{ .limitRate | default $defaults.limitRate | quote }}
    {{- end }}
    {{- if .limitRateAfter | default $defaults.limitRateAfter }}
    {{ $annoPrefix }}ingress.kubernetes.io/limit-rate-after: {{ .limitRateAfter | default $defaults.limitRateAfter | quote }}
    {{- end }}
    {{- if coalesce .limitRate $defaults.limitRate .limitRateAfter $defaults.limitRateAfter }}
    {{ $annoPrefix }}ingress.kubernetes.io/proxy-buffering: "on"
    {{- end }}
    {{- $limitWhitelistCidrs := .limitWhitelistCidrs | default $defaults.limitWhitelistCidrs }}
    {{- if $limitWhitelistCidrs }}
    {{ $annoPrefix }}ingress.kubernetes.io/limit-whitelist: |
      {{ range $limitWhitelistCidrs }}{{ . }},{{ end }}127.0.0.1/32
    {{- end }}
    {{- if .modsecurityEnabled | default $defaults.modsecurityEnabled }}
    {{ $annoPrefix }}ingress.kubernetes.io/enable-modsecurity: "true"
    {{ $annoPrefix }}ingress.kubernetes.io/modsecurity-transaction-id: "$request_id"
    {{- if .modsecurityRules | default $defaults.modsecurityRules }}
    {{ $annoPrefix }}ingress.kubernetes.io/enable-owasp-core-rules: "false"
    {{ $annoPrefix }}ingress.kubernetes.io/modsecurity-snippet: {{ .modsecurityRules | default $defaults.modsecurityRules }}
    {{- else }}
    {{ $annoPrefix }}ingress.kubernetes.io/enable-owasp-core-rules: "true"
    {{- end }}
    {{- else }}
    {{ $annoPrefix }}ingress.kubernetes.io/enable-modsecurity: "false"
    {{ $annoPrefix }}ingress.kubernetes.io/enable-owasp-core-rules: "false"
    {{- end }}
    {{- if .allowedCountries | default $defaults.allowedCountries }}
    {{ $annoPrefix }}ingress.kubernetes.io/server-snippet: |
      map $geoip2_city_country_code $allowed_country {
        default no;
        {{- range .allowedCountries | default $defaults.allowedCountries }}
        {{ . }} yes;
        {{- end }}
      }
    {{ $annoPrefix }}ingress.kubernetes.io/configuration-snippet: |
      if ($allowed_country = no) {
        return 444;
      }
    {{- else if .blockedCountries | default $defaults.blockedCountries }}
    {{ $annoPrefix }}ingress.kubernetes.io/server-snippet: |
      map $geoip2_city_country_code $blocked_country {
        default yes;
        {{- range .blockedCountries | default $defaults.blockedCountries }}
        {{ . }} no;
        {{- end }}
      }
    {{ $annoPrefix }}ingress.kubernetes.io/configuration-snippet: |
      if ($blocked_country) {
        return 444;
      }
    {{- end }}
    {{- $cidrs := .allowedCidrs | default $defaults.allowedCidrs }}
    {{- if $cidrs }}
    {{ $annoPrefix }}ingress.kubernetes.io/whitelist-source-range: |
      {{ range $i, $cidr := $cidrs }}{{ $cidr }},{{ end }}127.0.0.1/32
    {{- end }}
    {{- if .annotations }}
    {{- range $annotationName, $annotationValue := .annotations }}
    {{ $annotationName }}: {{ $annotationValue }}
    {{- end }}
    {{- end }}
spec:
  rules:
    {{- range $domain := $root.Values.ingress.domains }}
    - host: {{ $domain.name }}
      http:
        paths:
          {{- if or .rewriteTargetDisabled .rewriteTarget }}
          - path: {{ $path.path }}
          {{- else }}
          # TODO: remove oldRewritePolicy --> - path: {{ $path.path }}{{ "/?(.*)" }}
          - path: {{ $path.path }}{{ $root.Values.ingress.oldRewritePolicy | ternary "" "/?(.*)" }}
          {{- end }}
            backend:
              serviceName: {{ template "fullname" $root }}-{{ $serviceName }}
              servicePort: {{ $service.sidecar.port | default $defaults.port }}
    {{- end }}
---
{{- end }}
{{- end }}
{{- end }}
{{- end }}


{{- end }}

{{- end }}
{{- end }}

{{- end }}
{{- end }}
