{{- $root := . -}}
{{- $env := .Values.global.env -}}
{{- $global := .Values.global -}}
{{- $provider := .Values.global.zone.provider -}}
{{- $defaults := .Values.serviceDefaults -}}

{{- if .Values.networkPolicyEnabled}}

{{- /* TODO: network policies for cronjobs also */ -}}
{{- range $serviceName, $service := .Values.services }}
{{- with $service }}
{{- if or (not (hasKey . "enabled")) (.enabled) }}
{{- if or (not (hasKey . "serviceEnabled")) (.serviceEnabled) }}
{{- $type := default "service" .type -}}
{{- if or (eq "service" $type) (eq "external" $type) }}

{{- $fqdnPolicy := dict "enabled" false -}}
{{- range $egress := .egress }}
{{- if $egress.domain }}
{{ $dummy := set $fqdnPolicy "enabled" true }}
{{- end }}
{{- end }}

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "myfullname" $root }}-{{ $serviceName }}
spec:
  podSelector:
    matchLabels:
      app: {{ template "myname" $root }}
      release: {{ $root.Release.Name }}
      {{- if default $defaults.tier .tier }}
      tier: {{ default $defaults.tier .tier }}
      {{- end }}
      role: {{ $serviceName }}
  ingress:
  - from:
    - podSelector:
        matchLabels:
          access-{{ template "myfullname" $root }}-{{ $serviceName }}: "true"
  {{- if .paths }}
  {{- if gt (len .paths) 0 }}
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: {{ $root.Values.ingress.namespace }}
  {{- end }}
  {{- end }}

  {{- range $ingress := .ingress }}
  {{- if not $ingress.ip }}
  - from:
    - podSelector:
        matchLabels: {{ toJson (omit $ingress "namespace") }}
      {{- if $ingress.namespace }}
      namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: {{ $ingress.namespace }}
      {{- end }}
  {{- end }}

  {{- if $ingress.ip }}
  {{- if eq $ingress.ip "private" }}
  - from:
    - ipBlock:
        cidr: 10.0.0.0/8
  - from:
    - ipBlock:
        cidr: 172.16.0.0/12
  - from:
    - ipBlock:
        cidr: 192.168.0.0/16
  {{- else if eq $ingress.ip "any" }}
  - from:
    - ipBlock:
        cidr: 0.0.0.0/0
  {{- else }}
  - from:
    - ipBlock:
        cidr: {{ $ingress.ip }}
  {{- end }}
  {{- end }}

  {{- end }}
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system
    ports:
    - protocol: TCP
      port: 53  
    - protocol: UDP
      port: 53  
  {{- range $egress := .egress }}
  {{- if and (not $egress.ip) (not $egress.domain) }}
  - to:
    - podSelector:
        matchLabels: {{ toJson (omit $egress "namespace") }}
      {{- if $egress.namespace }}
      namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: {{ $egress.namespace }}
      {{- end }}
  {{- end }}
  {{- if $egress.ip }}
  {{- if eq $egress.ip "private" }}
  - to:
    - ipBlock:
        cidr: 10.0.0.0/8
  - to:
    - ipBlock:
        cidr: 172.16.0.0/12
  - to:
    - ipBlock:
        cidr: 192.168.0.0/16
  {{- else if eq $egress.ip "public" }}
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
        except:
          - 10.0.0.0/8
          - 172.16.0.0/12
          - 192.168.0.0/16
  {{- else if eq $egress.ip "any" }}
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
  {{- else }}
  - to:
    - ipBlock:
        cidr: {{ $egress.ip }}
  {{- end }}
  {{- end }}
  {{- end }}
---

{{- if $fqdnPolicy.enabled }}
apiVersion: networking.gke.io/v1alpha1
kind: FQDNNetworkPolicy
metadata:
  name: {{ template "myfullname" $root }}-{{ $serviceName }}
spec:
  podSelector:
    matchLabels:
      app: {{ template "myname" $root }}
      release: {{ $root.Release.Name }}
      {{- if default $defaults.tier .tier }}
      tier: {{ default $defaults.tier .tier }}
      {{- end }}
      role: {{ $serviceName }}
  egress:
  - matches:
    {{- range $egress := .egress }}
    {{- if $egress.domain }}
    - pattern: {{ $egress.domain | quote }}
    {{- end }}
    {{- end }}
---
{{- end }}

{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}

{{- end }}
