{{- $root := . -}}
{{- $env := .Values.global.env -}}
{{- $global := .Values.global -}}
{{- $provider := .Values.global.zone.provider -}}
{{- $defaults := .Values.serviceDefaults -}}

{{- if .Values.networkPolicyEnabled}}

# Default deny all for namespace
{{- if not $global.disableNamespaceInit }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
{{- end }}

{{- /* TODO: network policies for cronjobs also */ -}}
{{- range $serviceName, $service := .Values.services }}
{{- with $service }}
{{- if or (not (hasKey . "enabled")) (.enabled) }}
{{- $type := default "service" .type -}}
{{- if eq "service" $type }}

{{- $httpProxy := dict "enabled" false -}}
{{- range $egress := .egress }}
{{- if $egress.domain }}
{{ $dummy := set $httpProxy "enabled" true }}
{{- end }}
{{- end }}

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "fullname" $root }}-{{ $serviceName }}
spec:
  podSelector:
    matchLabels:
      app: {{ template "name" $root }}
      release: {{ $root.Release.Name }}
      {{- if default $defaults.tier .tier }}
      tier: {{ default $defaults.tier .tier }}
      {{- end }}
      role: {{ $serviceName }}
  ingress:
  - from:
    - podSelector:
        matchLabels:
          access-{{ template "fullname" $root }}-{{ $serviceName }}: "true"
  {{- if .paths }}
  {{- if gt (len .paths) 0 }}
  - from:
    - namespaceSelector:
        matchLabels:
          name: {{ $root.Values.ingress.namespace }}
  {{- end }}
  {{- end }}
  {{- range $ingress := .ingress }}
  - from:
    - podSelector:
        matchLabels: {{ toJson $ingress }}
  {{- end }}
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          networking/namespace: kube-system
      podSelector:
        matchLabels:
          k8s-app: kube-dns
  {{- if $httpProxy.enabled }}
  - to:
    - podSelector:
        matchLabels:
          fullname: {{ template "fullname" $root }}-{{ $serviceName }}-http-proxy
  {{- end }}
  {{- range $egress := .egress }}
  {{- if and (not $egress.ip) (not $egress.domain) }}
  - to:
    - podSelector:
        matchLabels: {{ toJson $egress }}
  {{- end }}
  {{- if $egress.ip }}
  {{- if eq $egress.ip "private" }}
  - to:
    - ipBlock:
        cidr: 10.0.0.0/8
  - to:
    - ipBlock:
        cidr: 172.16.0.0/12
  - to:
    - ipBlock:
        cidr: 192.168.0.0/16
  {{- else if eq $egress.ip "public" }}
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
        except:
          - 10.0.0.0/8
          - 172.16.0.0/12
          - 192.168.0.0/16
  {{- else if eq $egress.ip "any" }}
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
  {{- else }}
  - to:
    - ipBlock:
        cidr: {{ $egress.ip }}
  {{- end }}
  {{- end }}
  {{- end }}
---
{{- if $httpProxy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "fullname" $root }}-{{ $serviceName }}-http-proxy
spec:
  podSelector:
    matchLabels:
      app: {{ template "name" $root }}
      release: {{ $root.Release.Name }}
      tier: proxy
      role: {{ $serviceName }}-http-proxy
  ingress:
  - from:
    - podSelector:
        matchLabels:
          access-{{ template "fullname" $root }}-{{ $serviceName }}-http-proxy: "true"
  egress:
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
---
{{- end }}


{{- end }}
{{- end }}
{{- end }}
{{- end }}

{{- end }}
