{{- $root := . -}}

{{- if .Values.podSecurityPolicyCreate -}}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: {{ template "fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "fullname" . }}
    namespace: {{ .Release.Namespace }}
---
{{- end -}}

{{- range $role := .Values.serviceDefaults.serviceAccountRoles }}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: {{ template "fullname" $root }}-{{ $role }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ $role }}
subjects:
  - kind: ServiceAccount
    name: {{ template "fullname" $root }}
    namespace: {{ $root.Release.Namespace }}
---
{{- end }}
