{{- $root := . -}}
{{- $defaults := $root.Values.serviceDefaults -}}

{{- if or (not (hasKey $root.Values.ingress "enabled")) ($root.Values.ingress.enabled) }}
{{- if contains "openshift" $root.Values.ingress.class }}
{{- range $domain := $root.Values.ingress.domains }}
{{- range $serviceName, $service := $root.Values.services }}
{{- if or (not (hasKey $service "enabled")) ($service.enabled) }}
{{- range $path := $service.paths }}
{{- with $path }}

# OpenShift route
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ template "fullname" $root }}-{{ (split "." $domain.name)._0 }}-{{ $serviceName }}{{ $path.path | default "-root" | replace "/" "-" }}
  annotations:
  {{- if $root.Values.ingress.tls }}
    kubernetes.io/tls-acme: "true"
  {{- end }}
spec:
  host: {{ $domain.name }}
  {{- if $root.Values.ingress.tls }}
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  {{- end }}
  path: {{ $path.path }}
  port:
    targetPort: service
  to:
    kind: Service
    name: {{ template "fullname" $root }}-{{ $serviceName }}
    weight: 100
  wildcardPolicy: None
---

{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
