{{- $root := . -}}
{{- $defaults := .Values.serviceDefaults -}}

{{- if eq "gcp-gateway" $root.Values.ingress.class }}
{{- if or (not (hasKey $root.Values.ingress "enabled")) ($root.Values.ingress.enabled) }}

{{- range $serviceName, $service := $root.Values.services }}
{{- if or (not (hasKey $service "enabled")) ($service.enabled) }}
{{- range $path := $service.paths }}
{{- with $path }}
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ template "myfullname" $root }}-{{ $serviceName }}{{ .path | trimSuffix "/" | default "-root" | replace "/" "-" }}
  labels:
    gateway: {{ $root.Values.ingress.name }}
spec:
  parentRefs:
    - kind: Gateway
      name: {{ $root.Values.ingress.name }}
      namespace: {{ $root.Values.ingress.namespace }}
      sectionName: https
  hostnames:
  {{- range $domain := $root.Values.ingress.domains }}
  - {{ $domain.name }}
  {{- end }}
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: {{ $path.path }}{{ hasSuffix "/" $path.path | ternary "" "/" }}
    filters:
    - type: URLRewrite
      urlRewrite:
        path:
          type: ReplacePrefixMatch
          replacePrefixMatch: ""
    {{- if not .defaultCSPDisabled }}
    - type: ResponseHeaderModifier
      responseHeaderModifier:
        add:
          - name: Content-Security-Policy
            value: frame-ancestors 'none'
    {{- end }}
    backendRefs:
    - name: {{ template "myfullname" $root }}-{{ $serviceName }}
      port: {{ $service.port | default $defaults.port }}
---
{{- end }}
{{- end }}
{{- end }}
{{- end }}

{{- end }}
{{- end }}
