{{- $root := . -}}
{{- $defaults := .Values.serviceDefaults -}}

{{- range $serviceName, $service := .Values.services }}
{{- with $service }}
{{- if (or (not (hasKey . "enabled")) (.enabled)) }}
{{- $type := default "service" .type -}}
{{- if not (eq "job" $type) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" $root }}-{{ $serviceName }}
  labels:
    app: {{ template "name" $root }}
    chart: {{ $root.Chart.Name }}-{{ $root.Chart.Version | replace "+" "_" }}
    release: {{ $root.Release.Name }}
    heritage: {{ $root.Release.Service }}
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  selector:
    app: {{ template "name" $root }}
    release: {{ $root.Release.Name }}
    {{- if default $defaults.tier .tier }}
    tier: {{ default $defaults.tier .tier }}
    {{- end }}
    role: {{ $serviceName }}
  ports:
    - name: service
      port: {{ .port | default $defaults.port }}
      {{- if .targetPort }}
      targetPort: {{ .targetPort }}
      {{- end }}
    {{- range $p := .ports }}
    - port: {{ $p.port }}
      {{- if $p.targetPort }}
      targetPort: {{ $p.targetPort }}
      {{- end }}
    {{- end }}
    {{- if .sidecar }}
    {{- if .sidecar.enabled }}
    {{- if .sidecar.port }}
    - name: sidecar
      port: {{ .sidecar.port }}
      {{- if .sidecar.targetPort }}
      targetPort: {{ .sidecar.targetPort }}
      {{- end }}
    {{- range $p := .sidecar.ports }}
    - port: {{ $p.port }}
      {{- if $p.targetPort }}
      targetPort: {{ $p.targetPort }}
      {{- end }}
    {{- end }}
    {{- end }}
    {{- end }}
    {{- end }}
  {{- if eq $type "external" }}
  type: LoadBalancer
  {{- end }}
---
{{- end }}
{{- end }}
{{- end }}
{{- end }}
